# Signal Complete Script (Implementor)
# =====================================
# Signals task completion to the orchestrator.
# Creates a signal file that triggers verification.
#
# Usage: .\.orchestra\implementor\.implementor-only\scripts\signal-complete.ps1 -TaskId <id>
#
# Reference: Orchestra Bible Section 8.3

param(
    [Parameter(Mandatory=$false)]
    [string]$TaskId,
    [string]$Summary = ""
)

$ErrorActionPreference = "Stop"

# Load environment
$orchestraRoot = (Get-Item "$PSScriptRoot\..\..\..").FullName
. "$orchestraRoot\common\scripts\set-env.ps1" 2>$null

Write-Host "`n"
Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║              SIGNAL COMPLETION                               ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

# Get task ID from environment if not provided
if (-not $TaskId) {
    $TaskId = $env:CURRENT_TASK
}

if (-not $TaskId) {
    Write-Host "❌ Task ID required. Use -TaskId or set CURRENT_TASK env var." -ForegroundColor Red
    exit 1
}

Write-Host "  📋 Task ID: $TaskId" -ForegroundColor White

# Check pre-signal artifact exists
$artifactDir = "$orchestraRoot/implementor/artifacts/pre-signal"
$taskIdClean = $TaskId -replace '\.', '-'
$artifacts = Get-ChildItem -Path $artifactDir -Filter "task-$taskIdClean-*.txt" -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending

if (-not $artifacts) {
    Write-Host ""
    Write-Host "⚠️  No pre-signal artifact found." -ForegroundColor Yellow
    Write-Host "   Run pre-signal-check.ps1 first to validate your work." -ForegroundColor Yellow
    Write-Host ""
    $continue = Read-Host "Continue without pre-signal check? (y/N)"
    if ($continue -ne 'y') {
        exit 1
    }
} else {
    $latestArtifact = $artifacts[0]
    $artifactContent = Get-Content $latestArtifact.FullName -Raw
    
    if ($artifactContent -match 'status:\s*PASSED') {
        Write-Host "  ✅ Pre-signal check: PASSED" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️ Pre-signal check: FAILED" -ForegroundColor Yellow
        Write-Host "     You may want to fix issues before signaling." -ForegroundColor Yellow
    }
}

# Create signal file
$signalDir = "$orchestraRoot/implementor/signals"
if (-not (Test-Path $signalDir)) {
    New-Item -ItemType Directory -Path $signalDir -Force | Out-Null
}

$timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
$signalPath = "$signalDir/task-$taskIdClean-signal-$timestamp.yaml"

$signalContent = @"
# Completion Signal
# Generated by signal-complete.ps1

task_id: "$TaskId"
signaled_at: "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")"
signaled_by: "implementor"

pre_signal_check: $(if ($artifacts) { '"' + $latestArtifact.Name + '"' } else { "null" })

summary: |
  $Summary

# Orchestrator: Run gate-check and verification-audit to process this signal
"@

Set-Content -Path $signalPath -Value $signalContent -Encoding UTF8

Write-Host ""
Write-Host "  ✅ Signal created: $signalPath" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Cyan
Write-Host "    1. Notify orchestrator that signal is ready" -ForegroundColor White
Write-Host "    2. Orchestrator runs gate-check and verification" -ForegroundColor White
Write-Host "    3. Await feedback or completion confirmation" -ForegroundColor White
Write-Host ""

exit 0
