# Task {{task_id}}: {{task_title}}

## Overview

{{task_description}}

{{#if spec_file}}

## Spec Files

📄 **Task spec**: `{{spec_file}}`
{{#if command_spec}}
📄 **Command spec**: `{{command_spec}}`
{{/if}}

Please read the spec file(s) for full implementation details including code samples.
{{/if}}

{{#if depends_on.length}}

## Dependencies

These tasks must be completed first:
{{#each depends_on}}

- {{this}}
  {{/each}}
  {{/if}}

## ⚠️ BEFORE YOU START - MANDATORY VALIDATION

**STOP! Before implementing anything, validate this handover:**

```bash
orchestra status
```

If validation **FAILS**:

- Document issues in `.orchestra/handover/completion-signal.md`
- Say: "Task validation failed - see completion-signal.md"
- **STOP** and wait for orchestrator to fix

If validation **PASSES**: Proceed with implementation.

---

## Quality Gates

Before signaling completion:

1. **Build**: `npm run build` must succeed
2. **Type check**: `npx tsc --noEmit` must pass
3. **Tests**: `npm test` must pass all tests
4. **Lint**: `npm run lint` must pass (if configured)

## Completion Protocol

When ready for review:

1. Run pre-signal check:

   ```bash
   orchestra accept-signal
   ```

2. Update `.orchestra/handover/completion-signal.md` with:

   - Task ID and status
   - What was implemented
   - Test results
   - Any notes

3. Signal ready: Say "ready for review" or "task complete"

---

_This handover was generated by Orchestra. Do not read files in `.orchestra/orchestrator/.orchestrator-only/`._
